@API_URL = http://localhost:43526

@TOKEN = 

### BOOKS ROUTE    +++
GET {{API_URL}}/api/books

### EMPLOYEES ROUTE   +++
GET {{API_URL}}/api/employees

### FLASCHCARDS ROUTE   +++
GET {{API_URL}}/api/flaschcards

### GERMAN NOUNS ROUTE   +++
GET {{API_URL}}/api/germanNouns

### TECH ITEMS ROUTE   +++
GET {{API_URL}}/api/techitems

### TECH BOOKS ROUTE   +++
GET {{API_URL}}/api/techbooks

### BOOKID ROUTE    +++
GET {{API_URL}}/api/books/6391db1213287e7bc77e56e3

### EMPLOYEEID ROUTE   ++++
GET {{API_URL}}/api/employees/6391db2c13287e7bc77e5757

### FLASCHCARDID ROUTE   ++++
GET {{API_URL}}/api/flaschcards/6391db4113287e7bc77e5760

### GERMANNOUNID ROUTE   ++++
GET {{API_URL}}/api/germanNouns/6391db5413287e7bc77e58fd

### TECH ITEMID ROUTE   ++++
GET {{API_URL}}/api/techitems/6391db7613287e7bc77e595c

### TECHBOOKID ROUTE   ++++
GET {{API_URL}}/api/techbooks/6391db6713287e7bc77e5949